```{r, warning=FALSE}
library(Seurat)
library(SeuratObject)
library(sctransform)
library(dplyr)
library(ggplot2)
library(patchwork)
library(harmony)
```

### load seurat object
```{r}
mouse_exc <- readRDS('/restricted/projectnb/czproj/Projects/2025_CrossSpecies/SNSM_ROSMAP/snsm_orthologs_SCT.rds')
human_exc <- readRDS('/restricted/projectnb/czproj/Projects/2025_CrossSpecies/SNSM_ROSMAP/Entorhinal_cortex.rds')
mouse_exc_anno <- readRDS('/restricted/projectnb/czproj/Projects/2025_CrossSpecies/SNSM_ROSMAP/snsm_SCT_annotated.rds')
```

```{r}
mouse_exc$cell_type <- mouse_exc_anno$cell_type[colnames(mouse_exc)]
```

### extract interested samples
```{r}
samples_of_interest_mouse <- c('SNS2-2', 'SNS3_1', 'SNS3_2', 'SNS3_4')
samples_of_interest_human <- c('50400709', '76733461', '94430339', '50410319')

sample_subset_mouse <- subset(mouse_exc, subset = orig.ident %in% samples_of_interest_mouse)
sample_subset_human <- subset(human_exc, subset = projid %in% samples_of_interest_human)
```

### common genes
```{r}
common_genes <- intersect(gene_name_human, gene_name_mouse)
```

### pre-process before merge two subsets
```{r}
# set default assay
DefaultAssay(sample_subset_mouse) <- "RNA"
DefaultAssay(sample_subset_human) <- "RNA"

# Remove old SCT assay if it exists
sample_subset_mouse[["SCT"]] <- NULL
sample_subset_human[["SCT"]] <- NULL
sample_subset_human[["integrated"]] <- NULL

# select common genes
sample_subset_mouse <- subset(sample_subset_mouse, features = common_genes)
sample_subset_human <- subset(sample_subset_human, features = common_genes)

# change sample tags and add new tags based on species
sample_subset_mouse$sampleID <- sample_subset_mouse$orig.ident
sample_subset_mouse$orig.ident <- NULL

sample_subset_human$sampleID <- sample_subset_human$projid
sample_subset_human$projid <- NULL

sample_subset_mouse$dataset <- "mouse"
sample_subset_human$dataset <- "human"
```


### merge two datasets
```{r}
merged_obj <- merge(
  x = sample_subset_mouse, 
  y = sample_subset_human,
  project = "merged_mouse_human"
)

merged_obj$percent.mt <- NULL
merged_obj$nCount_SCT <- NULL
merged_obj$nFeature_SCT <- NULL
merged_obj$SCT_snn_res.1 <- NULL
merged_obj$seurat_clusters <- NULL
```

### split by sampleID (WHY???)
```{r}
merged_list <- SplitObject(merged_obj, split.by = "sampleID")
```

### normalization 

#### by SCT
```{r}
merged_list <- lapply(
  merged_list,
  function(obj) {
    obj <- SCTransform(obj, assay = 'RNA',vars.to.regress = "nFeature_RNA")
    obj[["SCT"]] <- obj@assays$SCT
    return(obj)
  }
)
```
### integration

#### Harmony
```{r}
# Merge — set SCT assay explicitly before merging
for (i in 1:length(merged_list)) {
  DefaultAssay(merged_list[[i]]) <- "SCT"
}

# Merge all objects
seurat_merged <- merge(merged_list[[1]], y = merged_list[-1])

# Now set SCT as default assay
DefaultAssay(seurat_merged) <- "SCT"

# Variable features
seurat_merged <- FindVariableFeatures(seurat_merged)

# PCA
seurat_merged <- RunPCA(seurat_merged)
```

```{r}
# Harmony
seurat_merged <- RunHarmony(seurat_merged, group.by.vars = "sampleID")
seurat_merged <- RunUMAP(seurat_merged, reduction = "harmony", dims = 1:30)
```

#### visualization
```{r}
# Split into a list of Seurat objects, one per sample
seurat_list <- SplitObject(seurat_merged, split.by = "sampleID")

# Save plots to PNG files
for (id in names(seurat_list)) {
  p <- DimPlot(seurat_list[[id]], reduction = "umap", group.by = 'sampleID') + ggtitle(id)
  ggsave(
    filename = paste0("SCT_Harmony_20k/UMAP_", id, ".png"),
    plot = p,
    width = 6,
    height = 5,
    dpi = 300
  )
}
```

```{r}
p <- DimPlot(seurat_merged, reduction = "umap", group.by = 'dataset')

ggsave(
    filename = "SCT_Harmony_20k/UMAP_dataset.png",
    plot = p,
    width = 6,
    height = 5,
    dpi = 300
  )
```

```{r}
p <- DimPlot(seurat_merged, reduction = "umap", group.by = 'dataset',split.by = 'dataset')

ggsave(
    filename = "SCT_Harmony_20k/UMAP_split_dataset.png",
    plot = p,
    width = 6,
    height = 5,
    dpi = 300
  )
```

```{r}
# Split Seurat objects into two species
seurat_list <- SplitObject(seurat_merged, split.by = "dataset")
```

```{r}
p <- DimPlot(seurat_list[[1]], reduction = "umap", group.by = 'cell_type')

ggsave(
    filename = "SCT_Harmony_20k/UMAP_mouse.png",
    plot = p,
    width = 8,
    height = 5,
    dpi = 300
  )
```

```{r}
p <- DimPlot(seurat_list[[2]], reduction = "umap", group.by = 'major_cell_type')

ggsave(
    filename = "SCT_Harmony_20k/UMAP_human.png",
    plot = p,
    width = 6,
    height = 5,
    dpi = 300
  )
```





